//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Title&quot;,&quot;Author&quot;,&quot;Genre&quot;,&quot;Publisher&quot;,&quot;Publication Year&quot;,&quot;ISBN&quot;,&quot;Language&quot;,&quot;Page Count&quot;,&quot;Format&quot;,&quot;Cover Type&quot;,&quot;Best Seller&quot;,&quot;Rating&quot;,&quot;Condition&quot;,&quot;Price&quot;,&quot;Availability&quot;
        ///&quot;Book Title 1&quot;,&quot;Author Name 1&quot;,&quot;Fantasy&quot;,&quot;Publisher Name 1&quot;,&quot;2020&quot;,&quot;1234567890123&quot;,&quot;English&quot;,&quot;320&quot;,&quot;Hardcover&quot;,&quot;Paperback&quot;,&quot;Yes&quot;,&quot;4.5&quot;,&quot;New&quot;,&quot;15.99&quot;,&quot;Yes&quot;
        ///&quot;Book Title 2&quot;,&quot;Author Name 2&quot;,&quot;Mystery&quot;,&quot;Publisher Name 2&quot;,&quot;2019&quot;,&quot;1234567890124&quot;,&quot;English&quot;,&quot;220&quot;,&quot;Paperback&quot;,&quot;Hardcover&quot;,&quot;No&quot;,&quot;3.8&quot;,&quot;Used&quot;,&quot;9.99&quot;,&quot;No&quot;
        ///&quot;Book Title 3&quot;,&quot;Author Name 3&quot;,&quot;Ro [rest of string was truncated]&qu....
        /// </summary>
        internal static string DataFile {
            get {
                return ResourceManager.GetString("DataFile", resourceCulture);
            }
        }
    }
}
